 # Main language/toolchain
language:
  - csharp

# Mono versions to test against
mono:
  - latest
  - 5.0.1

# Enable running inside a container (container-based infrastructure)
sudo:
  - false

# Install .NET Core
dotnet: 2.1.0-preview1-006547

# Default linux distro (Ubuntu 14.04)
dist:
  - trusty

# Global environment variables
env:
- BUILD_CONFIG="Debug" CACHE_NAME="Debug Build Cache"
- BUILD_CONFIG="Release" CACHE_NAME="Release Build Cache"

# Build script
script:
  - dotnet restore
  - dotnet build --configuration ${BUILD_CONFIG} EpubReader.sln
  - dotnet test Didstopia.EpubReader.Tests/Didstopia.EpubReader.Tests.csproj
  - dotnet pack

# Only build the master branch
branches:
  only:
    - master

# Caching
cache:
  directories:
  - $HOME/.nuget/packages
