 # Main language/toolchain
language: csharp

# Mono versions to test against
mono:
  - latest
  #- 5.0.1

# .NET Core versions to test against
#dotnet:
#- 1.0.4
#- 2.0.0-preview1-005977

# OS's to test against
os:
  - linux
  #- osx

# Disable sudo to enable running inside a container
sudo: false

# Default linux distro (Ubuntu 14.04)
dist: trusty

# Default Xcode/macOS version (macOS 10.12)
#osx_image: xcode8.3

# Global environment variables
env:
- BUILD_CONFIG="Debug" CACHE_NAME="Debug Build Cache" DOTNET_CLI_TELEMETRY_OPTOUT=1
#- BUILD_CONFIG="Release" CACHE_NAME="Release Build Cache" DOTNET_CLI_TELEMETRY_OPTOUT=1

# Install script
install:
  - bash <(curl -s https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh)
  - bash <(curl -s https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh) --channel "master" --version "latest"
  - ln -s $HOME/.dotnet/dotnet /usr/local/bin/dotnet

# Build script
script:
  - dotnet restore
  - dotnet build --configuration ${BUILD_CONFIG}
  #- dotnet test Didstopia.EpubReader.Tests/Didstopia.EpubReader.Tests.csproj
  - dotnet test Didstopia.EpubReader.Tests
  ## NuGet package creation seems to be broken on .NET 1.x, so we'd need to install 2.x to get it working again
  - dotnet pack

# Only build the master branch
branches:
  only:
    - master

# Caching
cache:
  directories:
  - $HOME/.nuget/packages
  - $HOME/.dotnet/NuGetFallbackFolder