 # Main language/toolchain
language: csharp

# Mono versions to test against
mono:
  - latest
  #- 5.0.1

# .NET Core versions to test against
dotnet: 2.0.0-preview1-005977

# OS's to test against
os:
  - linux
  #- osx

# Default linux distro (Ubuntu 14.04)
dist: trusty

# Default Xcode/macOS version (macOS 10.12)
#osx_image: xcode8.3

# Global environment variables
env:
- BUILD_CONFIG="Debug" CACHE_NAME="Debug Build Cache"
#- BUILD_CONFIG="Release" CACHE_NAME="Release Build Cache"

## Work around NuGet issue #2163
## https://github.com/NuGet/Home/issues/2163
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "Setting ulimit to 1024"; ulimit -n 1024; fi

# Build script
script:
  - dotnet restore
  - dotnet build --configuration ${BUILD_CONFIG}
  - dotnet test Didstopia.EpubReader.Tests/Didstopia.EpubReader.Tests.csproj
  ## NuGet package creation seems to be broken on .NET 1.x, so we'd need to install 2.x to get it working again
  #- dotnet pack

# Only build the master branch
branches:
  only:
    - master

# Caching
cache:
  directories:
  - $HOME/.nuget/packages